[package]
name = "gibbercode"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT OR ISC"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

itertools = "0.10.5"
